# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: who.fhir.smart-ot
canonical: http://worldhealthorganization.github.io/smart-ot
name: smart-ot
status: draft
version: 0.2.1
fhirVersion: 4.0.1
date: 2023-04-25
# copyright:
copyrightYear: 2021+
releaseLabel: "CI Build"
title: "WHO SMART Guideline: Surveillance and Outbreak Toolkit"
description: "WHO SMART Guideline: Surveillance and Outbreak Toolkit"
license: CC0-1.0
publisher:
  name: WHO
  url: http://who.int
email: leitnerc@who.int
# contact:
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001
# experimental: true
dependencies:  
  hl7.fhir.uv.sdc: 3.0.0


pages:
  index.xml:
    title: Home
  testing.md: 
    title: Testing
  license.md: 
    title: License
